/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bobobo;

import java.awt.BorderLayout;
import java.awt.Cursor;
import java.awt.Font;
import java.awt.Color;
import javafx.scene.layout.Border;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author IT-07
 */
public class game extends javax.swing.JFrame {
    private boolean sanalug=false;
    public String myname="";
    /**
     * Creates new form game
     */
    public game() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        closer = new javax.swing.JLabel();
        minimize = new javax.swing.JLabel();
        contentPanel = new javax.swing.JPanel();
        chatter = new javax.swing.JPanel();
        write = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        display = new javax.swing.JTextArea();
        chatlbl = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        peoplelbl = new javax.swing.JLabel();
        person2 = new javax.swing.JLabel();
        person3 = new javax.swing.JLabel();
        person1 = new javax.swing.JLabel();
        person4 = new javax.swing.JLabel();
        person5 = new javax.swing.JLabel();
        person6 = new javax.swing.JLabel();
        person7 = new javax.swing.JLabel();
        person8 = new javax.swing.JLabel();
        readyup = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        peoplelbl1 = new javax.swing.JLabel();
        joinbut = new javax.swing.JButton();
        readybut = new javax.swing.JButton();
        profile = new javax.swing.JPanel();
        Alive = new javax.swing.JLabel();
        status_bar = new javax.swing.JPanel();
        day_night = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(230, 126, 34));

        closer.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        closer.setText("x");
        closer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closerMouseClicked(evt);
            }
        });

        minimize.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        minimize.setText("-");
        minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 846, Short.MAX_VALUE)
                .addComponent(minimize, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(closer)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(closer, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minimize, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(81, Short.MAX_VALUE))
        );

        contentPanel.setBackground(new java.awt.Color(52, 152, 219));

        chatter.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        display.setEditable(false);
        display.setColumns(20);
        display.setRows(5);
        display.setFocusable(false);
        jScrollPane1.setViewportView(display);

        chatlbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        chatlbl.setForeground(new java.awt.Color(52, 73, 94));
        chatlbl.setText("Chat box");

        javax.swing.GroupLayout chatterLayout = new javax.swing.GroupLayout(chatter);
        chatter.setLayout(chatterLayout);
        chatterLayout.setHorizontalGroup(
            chatterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(write)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
            .addGroup(chatterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chatlbl)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        chatterLayout.setVerticalGroup(
            chatterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, chatterLayout.createSequentialGroup()
                .addComponent(chatlbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(write, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.setBackground(new java.awt.Color(236, 210, 94));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        peoplelbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        peoplelbl.setForeground(new java.awt.Color(52, 73, 94));
        peoplelbl.setText("Town's people");

        person2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        person2.setForeground(new java.awt.Color(52, 73, 94));
        person2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                person2MouseClicked(evt);
            }
        });

        person3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        person3.setForeground(new java.awt.Color(52, 73, 94));
        person3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                person3MouseClicked(evt);
            }
        });

        person1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        person1.setForeground(new java.awt.Color(52, 73, 94));
        person1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        person1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                person1MouseClicked(evt);
            }
        });

        person4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        person4.setForeground(new java.awt.Color(52, 73, 94));
        person4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                person4MouseClicked(evt);
            }
        });

        person5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        person5.setForeground(new java.awt.Color(52, 73, 94));
        person5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                person5MouseClicked(evt);
            }
        });

        person6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        person6.setForeground(new java.awt.Color(52, 73, 94));
        person6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                person6MouseClicked(evt);
            }
        });

        person7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        person7.setForeground(new java.awt.Color(52, 73, 94));

        person8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        person8.setForeground(new java.awt.Color(52, 73, 94));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(peoplelbl)
                        .addGap(0, 75, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(person8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(person7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(person5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(person4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                            .addComponent(person1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(person2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(person3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(person6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(peoplelbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(person1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(person2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(person3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(person4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(person5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(person6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(person7, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(person8, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 75, Short.MAX_VALUE))
        );

        readyup.setBackground(new java.awt.Color(155, 89, 182));

        peoplelbl1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        peoplelbl1.setForeground(new java.awt.Color(5, 32, 113));
        peoplelbl1.setText("Ready up!");

        joinbut.setText("Join game");
        joinbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                joinbutActionPerformed(evt);
            }
        });

        readybut.setText("Ready!");

        javax.swing.GroupLayout readyupLayout = new javax.swing.GroupLayout(readyup);
        readyup.setLayout(readyupLayout);
        readyupLayout.setHorizontalGroup(
            readyupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(readyupLayout.createSequentialGroup()
                .addGroup(readyupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(readyupLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(peoplelbl1))
                    .addGroup(readyupLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(joinbut)
                        .addGap(41, 41, 41)
                        .addComponent(readybut)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        readyupLayout.setVerticalGroup(
            readyupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(readyupLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(readyupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(peoplelbl1)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(readyupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(joinbut)
                    .addComponent(readybut))
                .addGap(26, 26, 26))
        );

        profile.setPreferredSize(new java.awt.Dimension(60, 60));

        Alive.setIcon(new javax.swing.ImageIcon(getClass().getResource("/zurag/big_flower.png"))); // NOI18N

        javax.swing.GroupLayout profileLayout = new javax.swing.GroupLayout(profile);
        profile.setLayout(profileLayout);
        profileLayout.setHorizontalGroup(
            profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Alive, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        profileLayout.setVerticalGroup(
            profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profileLayout.createSequentialGroup()
                .addComponent(Alive)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        status_bar.setBackground(new Color(0,0,0,0));

        day_night.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        day_night.setText("Day");

        javax.swing.GroupLayout status_barLayout = new javax.swing.GroupLayout(status_bar);
        status_bar.setLayout(status_barLayout);
        status_barLayout.setHorizontalGroup(
            status_barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(status_barLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(day_night)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        status_barLayout.setVerticalGroup(
            status_barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(status_barLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(day_night)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout contentPanelLayout = new javax.swing.GroupLayout(contentPanel);
        contentPanel.setLayout(contentPanelLayout);
        contentPanelLayout.setHorizontalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chatter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(profile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(contentPanelLayout.createSequentialGroup()
                        .addComponent(status_bar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(readyup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        contentPanelLayout.setVerticalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPanelLayout.createSequentialGroup()
                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contentPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(readyup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(status_bar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 159, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addGroup(contentPanelLayout.createSequentialGroup()
                .addComponent(chatter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(contentPanelLayout.createSequentialGroup()
                .addComponent(profile, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closerMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closerMouseClicked

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
        this.setState(ICONIFIED);
    }//GEN-LAST:event_minimizeMouseClicked

    private void joinbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_joinbutActionPerformed
        
    }//GEN-LAST:event_joinbutActionPerformed
    private boolean activated=false;
    private boolean sanalUguugui1=false;
    private void person1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_person1MouseClicked
        
        System.out.println(activated);
        if(activated){
            if(sanalUguugui1){
                sanalUguugui1=false;
                person1.setFont(new Font("Tahoma", Font.PLAIN, 12));
            }else{
                sanalUguugui1=true;
                person1.setFont(new Font("Tahoma", Font.BOLD, 13));
            }
            System.out.println(" "+sanalUguugui1);
        }
    }//GEN-LAST:event_person1MouseClicked
    private boolean sanalUguugui2=false;
    private void person2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_person2MouseClicked
        if(activated){
            if(sanalUguugui2){
                sanalUguugui2=false;
                person2.setFont(new Font("Tahoma", Font.PLAIN, 12));
            }else{
                sanalUguugui2=true;
                person2.setFont(new Font("Tahoma", Font.BOLD, 13));
            }
            System.out.println(" "+sanalUguugui2);
        }
    }//GEN-LAST:event_person2MouseClicked
    private boolean sanalUguugui3=false;
    private void person3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_person3MouseClicked
        if(activated){
            if(sanalUguugui3){
                sanalUguugui3=false;
                person3.setFont(new Font("Tahoma", Font.PLAIN, 12));
            }else{
                sanalUguugui3=true;
                person3.setFont(new Font("Tahoma", Font.BOLD, 13));
            }
            System.out.println(" "+sanalUguugui3);
        }
    }//GEN-LAST:event_person3MouseClicked
    private boolean sanalUguugui4=false;
    private void person4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_person4MouseClicked
        if(activated){
            if(sanalUguugui4){
                sanalUguugui4=false;
                person4.setFont(new Font("Tahoma", Font.PLAIN, 12));
            }else{
                sanalUguugui4=true;
                person4.setFont(new Font("Tahoma", Font.BOLD, 13));
            }
        }
    }//GEN-LAST:event_person4MouseClicked
    private boolean sanalUguugui5=false;
    private void person5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_person5MouseClicked
        if(activated){
            if(sanalUguugui5){
                sanalUguugui5=false;
                person5.setFont(new Font("Tahoma", Font.PLAIN, 12));
            }else{
                sanalUguugui5=true;
                person5.setFont(new Font("Tahoma", Font.BOLD, 13));
            }
        }
    }//GEN-LAST:event_person5MouseClicked
    private boolean sanalUguugui6=false;
    private void person6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_person6MouseClicked
        if(activated){
            if(sanalUguugui6){
                sanalUguugui6=false;
                person6.setFont(new Font("Tahoma", Font.PLAIN, 12));
            }else{
                sanalUguugui6=true;
                person6.setFont(new Font("Tahoma", Font.BOLD, 13));
            }
        }
    }//GEN-LAST:event_person6MouseClicked
    public void playerEntered(String sti){
        System.out.println(person1.getText());
        if("".equals(person1.getText())){
            person1.setText(sti);
        }else if("".equals(person2.getText())){
            person2.setText(sti);
        }else if("".equals(person3.getText())){
            person3.setText(sti);
        }else if("".equals(person4.getText())){
            person4.setText(sti);
        }else if("".equals(person5.getText())){
            person5.setText(sti);
        }else if("".equals(person6.getText())){
            person6.setText(sti);
        }else if("".equals(person7.getText())){
            person7.setText(sti);
        }else if("".equals(person8.getText())){
            person8.setText(sti);
        }
    }
    public void checkPolice(String str){
        if(myname.equals(str)) JOptionPane.showMessageDialog(this, "You are police");
    }
    public void checkDoctor(String str){
        if(myname.equals(str)) JOptionPane.showMessageDialog(this, "You are doctor");
    }
    public void checkMafia(String str){
        if(myname.equals(str)) JOptionPane.showMessageDialog(this, "You are Mafia");
    }
    public void gameStarted(){
        activated=true;
//        JOptionPane.showMessageDialog(this, "Toglolt ehellee");
        if(!"".equals(person1.getText())) person1.setCursor(new Cursor(Cursor.HAND_CURSOR));
        if(!"".equals(person2.getText())) person2.setCursor(new Cursor(Cursor.HAND_CURSOR));
        if(!"".equals(person3.getText())) person3.setCursor(new Cursor(Cursor.HAND_CURSOR));
        if(!"".equals(person4.getText())) person4.setCursor(new Cursor(Cursor.HAND_CURSOR));
        if(!"".equals(person5.getText())) person5.setCursor(new Cursor(Cursor.HAND_CURSOR));
        if(!"".equals(person6.getText())) person6.setCursor(new Cursor(Cursor.HAND_CURSOR));
        if(!"".equals(person7.getText())) person7.setCursor(new Cursor(Cursor.HAND_CURSOR));
        if(!"".equals(person8.getText())) person8.setCursor(new Cursor(Cursor.HAND_CURSOR));
        readyup.setVisible(false);
        //revalidate();
    }
    
    public void setRole(String s){
        this.role = s;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        //redefine
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new game().setVisible(true);
            }
        });
    }
    public JPanel getGamePanel(){
        this.chatter.setLayout(new BorderLayout());
        this.contentPanel.add(new javax.swing.JLabel("aash"));
        return this.chatter;
    }
    private String role ="none";
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Alive;
    private javax.swing.JLabel chatlbl;
    private javax.swing.JPanel chatter;
    private javax.swing.JLabel closer;
    public javax.swing.JPanel contentPanel;
    private javax.swing.JLabel day_night;
    public javax.swing.JTextArea display;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JButton joinbut;
    private javax.swing.JLabel minimize;
    private javax.swing.JLabel peoplelbl;
    private javax.swing.JLabel peoplelbl1;
    public javax.swing.JLabel person1;
    private javax.swing.JLabel person2;
    private javax.swing.JLabel person3;
    private javax.swing.JLabel person4;
    private javax.swing.JLabel person5;
    private javax.swing.JLabel person6;
    private javax.swing.JLabel person7;
    private javax.swing.JLabel person8;
    private javax.swing.JPanel profile;
    public javax.swing.JButton readybut;
    private javax.swing.JPanel readyup;
    private javax.swing.JPanel status_bar;
    public javax.swing.JTextField write;
    // End of variables declaration//GEN-END:variables
}
