/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Iderbat
 */
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.Timer;

public class Timers extends javax.swing.JFrame {

    /**
     * Creates new form Timer
     */
    
    int min , sec, min1, sec1 ; 
    Timer timer;
    boolean flag = true;
    boolean ifStop = false;
    public Timers() {
        initComponents();
        
        // minutiiin combobox iiiin selection uuud 
       for (int i = 0 ; i < 60 ; i++){
           minutcombobox.addItem(i);
       }
       
       // secondiiin combobox iiiin selection uuud 
       for (int i = 0 ; i < 60 ; i++){
           secondcomboBox.addItem(i);
       }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        secondlbl = new javax.swing.JLabel();
        minutlbl = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        minutcombobox = new javax.swing.JComboBox<>();
        secondcomboBox = new javax.swing.JComboBox<>();
        startBtn = new javax.swing.JButton();
        stopBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Timer");

        secondlbl.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        secondlbl.setText("00");

        minutlbl.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        minutlbl.setText("00");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel4.setText(":");

        minutcombobox.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        minutcombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minutcomboboxActionPerformed(evt);
            }
        });

        secondcomboBox.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        secondcomboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secondcomboBoxActionPerformed(evt);
            }
        });

        startBtn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        startBtn.setText("Start");
        startBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startBtnActionPerformed(evt);
            }
        });

        stopBtn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        stopBtn.setText("Stop");
        stopBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(138, 138, 138))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(startBtn)
                        .addGap(30, 30, 30)
                        .addComponent(stopBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(minutcombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(minutlbl))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(secondlbl)
                            .addComponent(secondcomboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(secondlbl)
                    .addComponent(minutlbl)
                    .addComponent(jLabel4))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(minutcombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(secondcomboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startBtn)
                    .addComponent(stopBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void minutcomboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minutcomboboxActionPerformed
        minutlbl.setText(""+minutcombobox.getSelectedIndex());
        min = Integer.parseInt(minutlbl.getText());
        
                
    }//GEN-LAST:event_minutcomboboxActionPerformed

    private void secondcomboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secondcomboBoxActionPerformed
        secondlbl.setText(""+secondcomboBox.getSelectedIndex());
        sec = Integer.parseInt(secondlbl.getText());
    }//GEN-LAST:event_secondcomboBoxActionPerformed

    private void startBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startBtnActionPerformed
        timer= new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if(min==0 && sec == 0){
                    JOptionPane.showMessageDialog(rootPane, "hugatsaagaaa oruulna uu !!!","ALERT", 0);
                    
                }
                if(ifStop){
                   min = min1;
                   sec = sec1;
                   ifStop = false;
                }

                if (sec == 0){
                    sec = 60;
                    min--;
                }
                
                
                //suuliin 10 secund nd orj irheer secund ulaan ungutei bolno
                if(sec <= 10 && min < 1){  
                    
                    secondlbl.setForeground(Color.red);
                }
                
                if (min<0){
                    JOptionPane.showMessageDialog(rootPane,"Za tsag duuslaa", "Stopped", 0);
                    min = 0 ; sec = 0; 
                    timer.stop();
                }else 
                {
                    
                sec--;
                if(sec < 10){
                    secondlbl.setText("0"+sec);
                    flag = false;
                }
                if(min<10){
                    minutlbl.setText("0"+min);
                    if(sec < 10)
                        secondlbl.setText("0"+sec);
                    else 
                        secondlbl.setText(""+sec);
                    flag = false;
                    
                }
                if(flag){
                
                
                minutlbl.setText(""+min);
                secondlbl.setText(""+sec);
                }
                }
            }
        });
        timer.start();
    }//GEN-LAST:event_startBtnActionPerformed

    private void stopBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopBtnActionPerformed
        min1 = min;
        sec1 = sec;
        ifStop = true;
        timer.stop();
        
    }//GEN-LAST:event_stopBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Timer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Timer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Timer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Timer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Timers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JComboBox<Integer> minutcombobox;
    private javax.swing.JLabel minutlbl;
    private javax.swing.JComboBox<Integer> secondcomboBox;
    private javax.swing.JLabel secondlbl;
    private javax.swing.JButton startBtn;
    private javax.swing.JButton stopBtn;
    // End of variables declaration//GEN-END:variables
}
